openapi.furnitureProductServiceAPISpecification.base-path: furniture-api
server.port: 8080
vives:
  shipmentservice.delayMs: 1000
  kafka:
    bootstrapAddress: localhost:29092
    consumer.groupId: vives
    order.topic: orders